language: java

jdk:
  - openjdk11
env:
  - NODE_VERSION="9.9.0"

cache:
  directories:
    - $HOME/.npm
    - .autoconf
    - $HOME/.m2

after_success:
  - mvn jacoco:report coveralls:report
  - $(npm bin)/cypress run --record --spec /home/travis/build/jasebook/jasebook-api/Cypress/integration/*.spec.*
  - ls
  - pwd
  - ls /home/travis/build/jasebook/jasebook-api/Cypress/integration


