language: java

jdk:
  - openjdk11
env:
  - NODE_VERSION="9.9.0"

before_install:
  - nvm install $NODE_VERSION

install:
  - npm ci

after_success:
  - mvn jacoco:report coveralls:report
  - $(npm bin)/cypress run --record


